[project]
name = "ComfyUI_XISER_Nodes"
description = "A feature-rich ComfyUI extension offering comprehensive visual editing capabilities: interactive multi-layer canvas with real-time transformations, professional PSD file import with layer extraction, versatile geometric shape generation with anti-aliased rendering, and advanced image processing tools. Includes batch shape creation, mask manipulation, prompt management, data flow optimization, and workflow enhancement utilities for efficient AI image generation and editing."
version = "1.3.1"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/grinlau18/ComfyUI_XISER_Nodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "xiser"
DisplayName = "ComfyUI_XISER_Nodes"
Icon = ""
